version: '3'

services:
  menuflow:
    image: bramenn/menuflow:stable
    restart: unless-stopped
    ports:
      - 29400:29400
    depends_on:
      - postgres
      - synapse
    volumes:
      - ./volumes/menuflow:/data
      - ./volumes/menuflow/flows:/data/flows
