# Homeserver details
homeserver:
    # The address that this menuflow can use to connect to the homeserver.
    address: https://example.com

menuflow:
  mxid: "@menuflow:example.com"
  access_token: "example_token"

  database: postgresql://username:password@hostname/dbname
  database_opts:
      min_size: 1
      max_size: 10

  # User to be ignored
  users_ignore:
  - '@whatsappbot:example.com'

server:
    # The IP and port to listen to.
    hostname: 0.0.0.0
    port: 29400
    # Public base URL where the server is visible.
    public_url: https://example.com
    # The base management API path.
    base_path: /_matrix/menuflow/v1

    # The shared secret to sign API access tokens.
    # Set to "generate" to generate and save a new token at startup.
    unshared_secret: generate

logging:
    version: 1
    formatters:
        normal:
            format: "[%(asctime)s] [%(levelname)s@%(name)s] %(message)s"
    handlers:
        file:
            class: logging.handlers.RotatingFileHandler
            formatter: normal
            filename: ./menuflow.log
            maxBytes: 10485760
            backupCount: 10
        console:
            class: logging.StreamHandler
    loggers:
        menuflow:
            level: DEBUG
        mau:
            level: DEBUG
        aiohttp:
            level: INFO
    root:
        level: DEBUG
        handlers: [file, console]


# TODO This section will be converted into db tables.
menu:
    id: Menu id

    # Nodes currently supported
    #   - message
    #   - input
    #   - http_request

    nodes:
    - id: 'm1'
      type: 'message'
      text: This is a menu that helps you to get 3 random news items
      o_connection: 'm2'

    - id: 'm2'
      type: 'input'
      variable: opt
      text: "
              We have the following categories:<br>
              1️⃣ All<br>
              2️⃣ National // Indian news only<br>
              3️⃣ Business<br>
              4️⃣ Sports<br>
              5️⃣ World<br>
              6️⃣ Politics<br>
              7️⃣ Technology<br>
              8️⃣ Startup<br>
              9️⃣ Entertainment<br>
              1️⃣0️⃣ Misc<br>
              1️⃣1️⃣ Hatke<br>
              1️⃣2️⃣ Science<br>
              1️⃣3️⃣ Automobile<br>
              Send your choice:
            "
      validation: "{{ opt }}"
      cases:
        - id: 1
          o_connection: r1
          variables:
            category: all
        - id: 2
          o_connection: r1
          variables:
            category: national
        - id: 3
          o_connection: r1
          variables:
            category: business
        - id: 4
          o_connection: r1
          variables:
            category: sports
        - id: 5
          o_connection: r1
          variables:
            category: world
        - id: 6
          o_connection: r1
          variables:
            category: politics
        - id: 7
          o_connection: r1
          variables:
            category: technology
        - id: 8
          o_connection: r1
          variables:
            category: startup
        - id: 9
          o_connection: r1
          variables:
            category: entertainment
        - id: 10
          o_connection: r1
          variables:
            category: miscellaneous
        - id: 11
          o_connection: r1
          variables:
            category: hatke
        - id: 12
          o_connection: r1
          variables:
            category: science
        - id: 13
          o_connection: r1
          variables:
            category: automobile
        - id: default
          o_connection: m2


    - id: 'r1'
      type: 'http_request'
      method: GET # POST
      url: https://inshorts.deta.dev/news?category={{category}}

      variables:
        news: data

      cases:
        - id: 200
          o_connection: m4
        - id: default
          o_connection: m5


    - id: 'm4'
      type: 'message'
      text: "
              {% for new in news %}

                {% if loop.index0 < 3 %}
                  {% set _new = news|random %}
                  ---<br>
                  **Title**: {{_new['title']}}<br>
                  **Author**: {{_new['author']}}<br>
                  **Date**: {{_new['date']}}<br>
                  **Image**: {{_new['imageUrl']}}<br>
                  {{_new['content']}}<br><br>
                {% endif%}
              {% endfor %}
            "
      o_connection: 'm1'

    - id: 'm5'
      type: 'message'
      text: "I did not find noting :("
      o_connection: 'm2'
