menuflow:
    database: postgresql://menuflow:secretfoo@postgres/menuflow
    database_opts:
        min_size: 1
        max_size: 10

    # Ignore messages from this users, it is a list of regex
    ignore_user_messages:
        - "@whatsappbot:example.com"
        - "@admin:example.com"

    ignore_invitations_from:
        - "@whatsappbot:example.com"
        - "@admin:example.com"
server:
    # The IP and port to listen to.
    hostname: 0.0.0.0
    port: 29400
    # Public base URL where the server is visible.
    public_url: https://example.com
    # The base management API path.
    base_path: /_matrix/menuflow/v1

    # The shared secret to sign API access tokens.
    # Set to "generate" to generate and save a new token at startup.
    unshared_secret: generate

utils:
    user_phone_regex: "^@(?P<user_prefix>.+)_(?P<number>[0-9]{8,}):.+$"

# Python logging configuration.
#
# See section 16.7.2 of the Python documentation for more info:
# https://docs.python.org/3.6/library/logging.config.html#configuration-dictionary-schema
logging:
    version: 1
    formatters:
        colored:
            (): menuflow.utils.color_log.ColorFormatter
            format: "[%(asctime)s] [%(levelname)s@%(name)s] %(message)s"
        normal:
            format: "[%(asctime)s] [%(levelname)s@%(name)s] %(message)s"
    handlers:
        file:
            class: logging.handlers.RotatingFileHandler
            formatter: normal
            filename: ./menuflow.log
            maxBytes: 10485760
            backupCount: 10
        console:
            class: logging.StreamHandler
            formatter: colored
    loggers:
        menuflow:
            level: DEBUG
        mau:
            level: DEBUG
        aiohttp:
            level: INFO
    root:
        level: DEBUG
        handlers: [file, console]
