whatsapp_bridge:
    mxid: '@whatsappbot:darknet'
ignore:
- '@whatsappbot:darknet'
menu:
    id: Menu id
    global_variables:
    - id: simple_flag
      value: Nice test

    pipelines:
    - id: 'p1'
      validation: '{{ opt }}'
      cases:
      - id: 1
        o_connection: 'm2'
      - id: 2
        o_connection: 'm3'
      - id: default
        o_connection: 'm3'

    - id: 'p2'
      validation: "{% '^[a-z0-9]+[\\._]?[a-z0-9]+[@]\\w+[.]\\w{2,3}$' | validate_regex %}"
      cases:
      - id: true
        o_connection: 'm3'
      - id: false
        o_connection: 'm4'
      - id: default
        o_connection: 'm5'

    - id: 'p3'
      validation: '{{ dni.isdigit() }}'
      cases:
      - id: true
        o_connection: 'm6'
      - id: false
        o_connection: 'm5'

    messages:
    - id: 'm1'
      text: Hello **Welcome** to MenuFlow test menu
      o_connection: 'm2'

    - id: 'm2'
      text: "Please enter your name:"
      o_connection: 'm3'
      variable: name


    - id: 'm3'
      text: "Nice talking to you **{name}**"
      o_connection: 'm4'

    - id: 'm4'
      text: "**{name}** please enter your ID number:"
      variable: dni
      o_connection: 'p3'

    - id: 'm5'
      text: "**{dni}** is not an ID number"
      o_connection: 'm4'

    - id: 'm6'
      text: "Thank you very much **{name}**, your ID number is {dni}"
      o_connection: 'm7'

    - id: 'm7'
      text: "See you next time"
      o_connection: 'm1'
