users_ignore:
- '@whatsappbot:localhost'

menu:
    id: Menu id

    # Nodes currently supported
    #   - message
    #   - input
    #   - http_request

    nodes:
    - id: 'm1'
      type: 'message'
      text: "Hola **productor** bienvenido, este menú te ayudara a registrar producciones o proyecciones de tus cultivos"
      o_connection: 'r1'

    # Login en aicampo
    - id: 'r1'
      type: 'http_request'
      method: POST # POST
      url: https://api.aicampo.com/core/user/login

      basic_auth:
        login: "bot@admin.co"
        password: "asdfgH123$"

      data:
        SOFTWARE: aicampo

      cookies:
        token: signedToken

      cases:
        - id: 200
          o_connection: r2
        - id: default
          o_connection: m3

    # Obtener información del productor
    - id: 'r2'
      type: 'http_request'
      method: GET # POST
      url: https://api.aicampo.com/core/user/?where=mobile={{user_phone}}

      basic_auth:
        login: "bot@admin.co"
        password: "asdfgH123$"

      variables:
        user_info: body

      cases:
        - id: 200
          o_connection: m2
        - id: default
          o_connection: m3


    - id: 'm2'
      type: 'message'
      text: "
                {% for user in user_info %}
                    **{{user['name']}}** Es un placer hablar contigo
                {% endfor %}
            "
      o_connection: 'm1'


    - id: 'm3'
      type: 'message'
      text: "No hemos podido indentificarnos"
      o_connection: 'm1'
