whatsapp_bridge:
    mxid: '@whatsappbot:darknet'

ignore_list:
    - "@whatsappbot:darknet"

menu:
    id: Menu id
    variables:
    - id: "$opt"
      data: ""

    filters:
    - id: "#filter_1"
      o_connection: "#message_1"
      else_o_connection: "#message_2"
      validations:
      - var_x: "$opt"
        var_y: 1
        operator: IS_EQUAL

    messages:
    - id: "#origin"
      text: "Ingrese:\n1- Para mas información \nOtra cosa para error"
      i_connection: "#origin"
      o_connection: "#filter_1"

      variable: "$opt"

      i_rule: NUMBER
      i_rule_fail_message: No sabemos que hacer con este mensaje


    - id: "#message_1"
      text: Rebien papi

    - id: "#message_2"
      text: Error
