users_ignore:
- '@whatsappbot:darknet'

menu:
    id: Menu id

    # Nodes currently supported
    #   - message
    #   - input
    #   - http_request

    nodes:
    - id: 'm1'
      type: 'message'
      text: Hello **Welcome** to MenuFlow
      o_connection: 'm2'

    - id: 'm2'
      type: 'input'
      text: "Please enter a pokemon name:"
      o_connection: 'm3'
      variable: pokemon_name

    - id: 'm3'
      type: 'message'
      text: "Ok, let's look for information about {{ pokemon_name }}"
      o_connection: 'r1'

    - id: 'r1'
      type: 'http_request'
      method: GET # POST
      url: https://pokeapi.co/api/v2/pokemon/{{ pokemon_name }}

      variables:
        pokemon: name
        height: height
        weight: weight
        base_experience: base_experience

      cases:
        - id: 200
          o_connection: m4
        - id: 404
          o_connection: m5

    - id: 'm4'
      type: 'message'
      text: "I found that {{pokemon_name}} has a height of {{height}} a weight of {{weight}} and its experience base is {{base_experience}}"
      o_connection: 'm1'

    - id: 'm5'
      type: 'message'
      text: "I did not find {{pokemon_name}} :("
      o_connection: 'm2'
