whatsapp_bridge:
    mxid: '@whatsappbot:darknet'
menu:
    id: Menu id
    variables:
    - id: test
      data: 1500
    - id: prueba
      data: 2500

    filters:
    - id: r1
      validations:
      - o_connection: a2
        else_o_connection: a2
        var_x: prueba
        var_y: test
        operator: IS_EQUAL

    messages:
    - id: origin
      text: Ingrese un numero porfavor
      i_connection: origin
      o_connection: r1

      i_rule: NUMBER
      i_rule_fail_message: No sabemos que hacer con este mensaje


    - id: a2
      text: Rebien papi

    - id: a3
      text: Error
