whatsapp_bridge:
    mxid: '@whatsappbot:darknet'

ignore_list:
    - "@whatsappbot:darknet"

menu:
    id: Menu id

    global_variables:
      - id: email_regex
        value: "^[a-z0-9]+[\._]?[a-z0-9]+[@]\w+[.]\w{2,3}$"

    filters:
    - id: "#filter_1"
      validation: "{% opt|switch %}"
      cases:
        - id: 1
          value: "#message_1"
        - id: 2
          value: "#message_2"
        - id: default
          value: "#message_3"

    - id: "#filter_2"
      variable: email
      validation: "{% email_regex|validate_regex %}"
      o_connection: "#message_3"
      else_o_connection: "#message_4"

    - id: "#filter_3"
      validation: "{{ opt.isdigit() }}"
      o_connection: "#filter_1"
      else_o_connection: "#message_5"

    messages:
    - id: "#origin"
      text: "Ingrese:\n1- Para mas información \nOtra cosa para error"
      variable: opt
      o_connection: "#filter_3"

    - id: "#message_1"
      text: Enviame un email
      variable: email
      o_connection: "#filter_2"


    - id: "#message_2"
      text: Segundo mensaje

    - id: "#message_3"
      text: Todo termina aqui

    - id: "#message_4"
      text: Esto no es un email

    - id: "#message_5"
      text: No sabemos que hacer con este mensaje