whatsapp_bridge:
    mxid: '@whatsappbot:darknet'
ignore:
- '@whatsappbot:darknet'
menu:
    id: Menu id
    global_variables:
    - id: simple_flag
      value: Nice test

    # We can have different types of nodes.
    # if they start with:
    # "m" -> Message
    # "r" -> HTTP Request

    nodes:
    - id: 'm1'
      text: Hello **Welcome** to MenuFlow test menu
      o_connection: 'm2'

    - id: 'm2'
      text: "Please enter your name:"
      o_connection: 'm3'
      variable: name


    - id: 'm3'
      text: "Nice talking to you **{name}**"
      o_connection: 'm4'

    - id: 'm4'
      text: "**{name}** please enter your ID number:"
      variable: dni
      validation: '{{ dni.isdigit() }}'
      cases:
      - id: true
        o_connection: 'm6'
      - id: false
        o_connection: 'm5'

    - id: 'r1'
      metohd: GET # POST
      url: https://randomuser.me/api/
      # query_params:
      #   "foo": "foo"
      # headers:
      #   "foo": "foo"
      # data:
      #   "user_email": "foo@foo.com"
      #   "phone": "{phone}"
      variables:
        name: results.0.name.first
        email: results.0.email
        city: results.0.location.city
        version: version
        # all_results: resutls
        # all_results_names: resutls.[].name.first
        # all_results_email: resutls.[].email

      response:
        status:
          - id: 200
            o_connection: m5
          - id: 404
            o_connection: m6

    - id: 'm5'
      text: "**{dni}** is not an ID number"
      o_connection: 'm4'

    - id: 'm6'
      text: "Thank you very much **{name}**, your ID number is {dni}"
      o_connection: 'm7'

    - id: 'm7'
      text: "See you next time"
      o_connection: 'm1'
